### ISSUE TITLE
Um It's not working!

### ISSUE THREAD

**Issue by falceso** [falceso/ServerManagement#2]
@Hontu the plugin is not working for some reason................... The login message system does not show anything.

**Comment by falceso** [comment]
#1

**Comment by falceso** [comment]
#2 @xyuchi

**Comment by MicahManlapeg** [comment]
Nice plugin so far, i'll fork it and edit it @falceso.

**Comment by MicahManlapeg** [comment]
^^ bump, there isn't any errors I think. Is EssentialsChat enabled on your server?

**Comment by falceso** [comment]
Wait a minute... WHAT
